In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mlsp2-nn-model/model2_NN.h5
/kaggle/input/test-set/test/X/melspec_349.npy
/kaggle/input/test-set/test/X/melspec_2250.npy
/kaggle/input/test-set/test/X/melspec_1843.npy
/kaggle/input/test-set/test/X/melspec_1328.npy
/kaggle/input/test-set/test/X/melspec_1587.npy
/kaggle/input/test-set/test/X/melspec_501.npy
/kaggle/input/test-set/test/X/melspec_1568.npy
/kaggle/input/test-set/test/X/melspec_2180.npy
/kaggle/input/test-set/test/X/melspec_1776.npy
/kaggle/input/test-set/test/X/melspec_1804.npy
/kaggle/input/test-set/test/X/melspec_1962.npy
/kaggle/input/test-set/test/X/melspec_255.npy
/kaggle/input/test-set/test/X/melspec_1623.npy
/kaggle/input/test-set/test/X/melspec_390.npy
/kaggle/input/test-set/test/X/melspec_1375.npy
/kaggle/input/test-set/test/X/melspec_227.npy
/kaggle/input/test-set/test/X/melspec_1138.npy
/kaggle/input/test-set/test/X/melspec_880.npy
/kaggle/input/test-set/test/X/melspec_2201.npy
/kaggle/input/test-set/test/X/melspec_798.npy
/kaggle/input/test-set/te

In [3]:
import tensorflow as tf
import os
import numpy as np
from sklearn.model_selection import train_test_split
lst_names = os.listdir("../input/assign-2-val/X_new")
file_names = []
for m in range(len(lst_names)):
    file_names.append(lst_names[m][9:])

In [ ]:
x_train = []
for m in range(10000):
    z = np.load("../input/assign-2-train/X_new/melspec1_" + str(m) + ".npy")
    z = np.reshape(z,(64,1000,1))
    x_train.append(z)
for m in range(2000):
    z = np.load("../input/assign-2-val/X_new/melspec1_" + file_names[m])
    z = np.reshape(z,(64,1000,1))
    x_train.append(z)
x_train = np.array(x_train)
x_train.shape 

In [ ]:
y_train = []
for m in range(10000):
    y_train.append(np.load("../input/assign-2-train/Y_new/eventroll1_" + str(m) + ".npy"))
for m in range(2000):
    y_train.append(np.load("../input/assign-2-val/Y_new/eventroll1_" + file_names[m]))
y_train = np.array(y_train)
y_train.shape

In [5]:
from sklearn.utils import shuffle
x_train, y_train = shuffle(x_train, y_train)
x_train, x_valid, y_train, y_valid = train_test_split(x_train, y_train, random_state=42, test_size=0.167)

In [ ]:
(temp, f, t, num) = x_train.shape 
(temp, f, t, num)

In [10]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import BatchNormalization

In [13]:
model = Sequential()
model.add(tf.keras.layers.Input(shape=(f, t, num)))
model.add(Flatten())
model.add(Dense(1024, activation='leaky_relu'))
model.add(BatchNormalization())
model.add(Dense(256, activation='leaky_relu'))
model.add(BatchNormalization())
model.add(Dense(64, activation='leaky_relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(10, activation='sigmoid'))

In [14]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 64000)             0         
_________________________________________________________________
dense_4 (Dense)              (None, 1024)              65537024  
_________________________________________________________________
batch_normalization_3 (Batch (None, 1024)              4096      
_________________________________________________________________
dense_5 (Dense)              (None, 256)               262400    
_________________________________________________________________
batch_normalization_4 (Batch (None, 256)               1024      
_________________________________________________________________
dense_6 (Dense)              (None, 64)                16448     
_________________________________________________________________
batch_normalization_5 (Batch (None, 64)               

In [15]:
model.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(),
    metrics=[tf.keras.metrics.Precision(),tf.keras.metrics.Recall(), ],
)

history = model.fit(x_train, y_train, verbose = 1, epochs=40, batch_size = 32, validation_data=(x_valid, y_valid))

2022-11-12 11:14:52.015646: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2560000000 exceeds 10% of free system memory.
2022-11-12 11:14:54.974561: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2560000000 exceeds 10% of free system memory.
2022-11-12 11:14:56.984549: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/40
313/313 [==============================] - ETA: 0s - loss: 0.6161 - precision: 0.3542 - recall: 0.5330

2022-11-12 11:15:03.548529: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 512000000 exceeds 10% of free system memory.


313/313 [==============================] - 8s 18ms/step - loss: 0.6161 - precision: 0.3542 - recall: 0.5330 - val_loss: 0.3879 - val_precision: 0.7518 - val_recall: 0.4145
Epoch 2/40
313/313 [==============================] - 5s 15ms/step - loss: 0.3845 - precision: 0.7220 - recall: 0.4896 - val_loss: 0.3582 - val_precision: 0.7591 - val_recall: 0.4132
Epoch 3/40
313/313 [==============================] - 5s 15ms/step - loss: 0.3515 - precision: 0.7812 - recall: 0.4889 - val_loss: 0.3531 - val_precision: 0.7740 - val_recall: 0.4118
Epoch 4/40
313/313 [==============================] - 5s 15ms/step - loss: 0.3326 - precision: 0.8141 - recall: 0.5119 - val_loss: 0.3423 - val_precision: 0.7584 - val_recall: 0.4460
Epoch 5/40
313/313 [==============================] - 5s 15ms/step - loss: 0.3201 - precision: 0.8246 - recall: 0.5264 - val_loss: 0.3513 - val_precision: 0.7636 - val_recall: 0.4308
Epoch 6/40
313/313 [==============================] - 5s 15ms/step - loss: 0.3083 - precision: 0

In [23]:
model.save('model2.h5')

2022-11-12 11:19:37.433681: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 262144000 exceeds 10% of free system memory.


In [16]:
yhat_probs = model.predict(x_valid, verbose=1)

2022-11-12 11:18:27.146998: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 512000000 exceeds 10% of free system memory.


63/63 [==============================] - 0s 6ms/step


In [17]:
yhat1 = yhat_probs.round()

In [18]:
yhat1

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 1., 0.]], dtype=float32)

In [19]:
y_valid

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 1., 0.]])

In [4]:
events_types = ['Alarm_bell_ringing', 'Blender','Cat','Dishes','Dog','Electric_shaver_toothbrush','Frying','Running_water','Speech','Vacuum_cleaner']

In [21]:
from sklearn.metrics import classification_report
report = classification_report(y_valid, yhat1, output_dict=True, target_names = events_types)
report_df = pd.DataFrame(report).transpose()

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
report_df

precision    recall  f1-score  support
Alarm_bell_ringing           0.352332  0.204819  0.259048    332.0
Blender                      0.266176  0.551829  0.359127    328.0
Cat                          0.428571  0.078603  0.132841    229.0
Dishes                       0.388535  0.246465  0.301607    495.0
Dog                          0.541667  0.081505  0.141689    319.0
Electric_shaver_toothbrush   0.473684  0.639594  0.544276    197.0
Frying                       0.742515  0.613861  0.672087    202.0
Running_water                0.750000  0.137755  0.232759    196.0
Speech                       0.889671  0.735446  0.805241   1546.0
Vacuum_cleaner               0.562500  0.284211  0.377622    190.0
micro avg                    0.603526  0.466782  0.526419   4034.0
macro avg                    0.539565  0.357409  0.382630   4034.0
weighted avg                 0.629685  0.466782  0.504206   4034.0
samples avg                  0.530167  0.455517  0.469511   4034.0

In [5]:
model1 = tf.keras.models.load_model('../input/mlsp2-nn-model/model2_NN.h5')

2022-11-13 10:34:08.992649: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 10:34:09.109846: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 10:34:09.110622: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 10:34:09.111987: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

In [7]:
x_test = []
for m in range(2500):
    z = np.load("../input/test-set/test/X/melspec_" + str(m) + ".npy")
    z = np.reshape(z,(64,1000,1))
    x_test.append(z)
x_test = np.array(x_test)
x_test.shape

(2500, 64, 1000, 1)

In [8]:
model1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten_1 (Flatten)          (None, 64000)             0         
_________________________________________________________________
dense_4 (Dense)              (None, 1024)              65537024  
_________________________________________________________________
batch_normalization_3 (Batch (None, 1024)              4096      
_________________________________________________________________
dense_5 (Dense)              (None, 256)               262400    
_________________________________________________________________
batch_normalization_4 (Batch (None, 256)               1024      
_________________________________________________________________
dense_6 (Dense)              (None, 64)                16448     
_________________________________________________________________
batch_normalization_5 (Batch (None, 64)               

In [9]:
yhat_probs = model1.predict(x_test, verbose=1)
yhat1 = yhat_probs.round()
print(yhat1)
print(len(yhat1))

2022-11-13 10:35:30.406254: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


79/79 [==============================] - 2s 5ms/step
[[1. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
2500


In [10]:
lst = []
c = 0
for m in yhat1:
    z = []
    if m[0] == 1:
        z.append(events_types[0])
    if m[1] == 1:
        z.append(events_types[1])
    if m[2] == 1:
        z.append(events_types[2])
    if m[3] == 1:
        z.append(events_types[3])
    if m[4] == 1:
        z.append(events_types[4])
    if m[5] == 1:
        z.append(events_types[5])
    if m[6] == 1:
        z.append(events_types[6])
    if m[7] == 1:
        z.append(events_types[7])
    if m[8] == 1:
        z.append(events_types[8])
    if m[9] == 1:
        z.append(events_types[9])
    lst.append(z)

In [11]:
lst

[['Alarm_bell_ringing', 'Speech'],
 ['Dishes', 'Frying', 'Speech'],
 ['Electric_shaver_toothbrush', 'Speech'],
 ['Dog', 'Speech'],
 ['Blender'],
 ['Dog', 'Speech'],
 ['Blender', 'Speech'],
 ['Blender', 'Speech'],
 ['Blender', 'Speech'],
 ['Blender', 'Speech'],
 ['Speech'],
 ['Speech'],
 ['Blender', 'Speech'],
 ['Frying', 'Speech'],
 ['Blender', 'Speech'],
 ['Electric_shaver_toothbrush', 'Speech'],
 ['Alarm_bell_ringing', 'Speech'],
 ['Blender', 'Speech'],
 ['Blender', 'Dishes', 'Speech'],
 ['Speech', 'Vacuum_cleaner'],
 ['Dishes', 'Frying', 'Speech'],
 ['Speech', 'Vacuum_cleaner'],
 ['Blender', 'Speech'],
 ['Blender', 'Dishes'],
 ['Speech', 'Vacuum_cleaner'],
 ['Running_water', 'Speech'],
 ['Blender', 'Dishes', 'Speech'],
 ['Speech'],
 ['Blender', 'Dishes', 'Speech'],
 ['Electric_shaver_toothbrush', 'Speech'],
 ['Blender', 'Dishes', 'Frying', 'Speech'],
 ['Electric_shaver_toothbrush', 'Speech'],
 ['Blender', 'Speech'],
 ['Speech'],
 ['Blender', 'Speech'],
 ['Blender', 'Speech'],
 ['Ble

In [12]:
lst_names = []
for m in range(2500):
    lst_names.append("melspec_" + str(m) + ".npy")

In [13]:
import pandas as pd
df = pd.DataFrame(list(zip(lst_names, lst)),
               columns =['fileid', 'prediction'])
df

fileid                            prediction
0        melspec_0.npy          [Alarm_bell_ringing, Speech]
1        melspec_1.npy              [Dishes, Frying, Speech]
2        melspec_2.npy  [Electric_shaver_toothbrush, Speech]
3        melspec_3.npy                         [Dog, Speech]
4        melspec_4.npy                             [Blender]
...                ...                                   ...
2495  melspec_2495.npy                      [Dishes, Speech]
2496  melspec_2496.npy                              [Speech]
2497  melspec_2497.npy                              [Speech]
2498  melspec_2498.npy  [Electric_shaver_toothbrush, Speech]
2499  melspec_2499.npy              [Dishes, Frying, Speech]

[2500 rows x 2 columns]

In [14]:
df.to_csv("model_4_NN_test_result.csv")