In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/test-set/test/X/melspec_349.npy
/kaggle/input/test-set/test/X/melspec_2250.npy
/kaggle/input/test-set/test/X/melspec_1843.npy
/kaggle/input/test-set/test/X/melspec_1328.npy
/kaggle/input/test-set/test/X/melspec_1587.npy
/kaggle/input/test-set/test/X/melspec_501.npy
/kaggle/input/test-set/test/X/melspec_1568.npy
/kaggle/input/test-set/test/X/melspec_2180.npy
/kaggle/input/test-set/test/X/melspec_1776.npy
/kaggle/input/test-set/test/X/melspec_1804.npy
/kaggle/input/test-set/test/X/melspec_1962.npy
/kaggle/input/test-set/test/X/melspec_255.npy
/kaggle/input/test-set/test/X/melspec_1623.npy
/kaggle/input/test-set/test/X/melspec_390.npy
/kaggle/input/test-set/test/X/melspec_1375.npy
/kaggle/input/test-set/test/X/melspec_227.npy
/kaggle/input/test-set/test/X/melspec_1138.npy
/kaggle/input/test-set/test/X/melspec_880.npy
/kaggle/input/test-set/test/X/melspec_2201.npy
/kaggle/input/test-set/test/X/melspec_798.npy
/kaggle/input/test-set/test/X/melspec_980.npy
/kaggle/input/test-se

In [2]:
import tensorflow as tf
import os
import numpy as np
from sklearn.model_selection import train_test_split
lst_names = os.listdir("../input/assign-2-val/X_new")
file_names = []
for m in range(len(lst_names)):
    file_names.append(lst_names[m][9:])
file_names

In [ ]:
x_train = []
for m in range(10000):
    z = np.load("../input/assign-2-train/X_new/melspec1_" + str(m) + ".npy")
    z = np.reshape(z,(64,1000,1))
    x_train.append(z)
for m in range(2000):
    z = np.load("../input/assign-2-val/X_new/melspec1_" + file_names[m])
    z = np.reshape(z,(64,1000,1))
    x_train.append(z)
x_train = np.array(x_train)
x_train.shape  

In [ ]:
y_train = []
for m in range(10000):
    y_train.append(np.load("../input/assign-2-train/Y_new/eventroll1_" + str(m) + ".npy"))
for m in range(2000):
    y_train.append(np.load("../input/assign-2-val/Y_new/eventroll1_" + file_names[m]))
y_train = np.array(y_train)
y_train.shape

In [5]:
from sklearn.utils import shuffle
x_train, y_train = shuffle(x_train, y_train)
x_train, x_valid, y_train, y_valid = train_test_split(x_train, y_train, random_state=42, test_size=0.167)

In [ ]:
(temp, f, t, num) = x_train.shape 
(temp, f, t, num)

In [7]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization

In [8]:
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(3, 3), activation="leaky_relu", input_shape=(f, t, num)))
model.add(BatchNormalization())
model.add(Dropout(0.25))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation='relu'))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(filters=64, kernel_size=(3, 3), activation="relu"))
model.add(BatchNormalization())
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.5))
model.add(Flatten())
model.add(Dense(128, activation='leaky_relu'))
model.add(BatchNormalization())
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='sigmoid'))

2022-11-13 06:17:29.455487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 06:17:29.555561: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 06:17:29.556489: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 06:17:29.557960: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 998, 32)       320       
_________________________________________________________________
batch_normalization (BatchNo (None, 62, 998, 32)       128       
_________________________________________________________________
dropout (Dropout)            (None, 62, 998, 32)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 60, 996, 64)       18496     
_________________________________________________________________
batch_normalization_1 (Batch (None, 60, 996, 64)       256       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 30, 498, 64)       0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 30, 498, 64)       0

In [10]:
model.compile(
    loss='binary_crossentropy',
    optimizer=tf.keras.optimizers.Adam(),
    metrics=[tf.keras.metrics.Precision(),tf.keras.metrics.Recall(), ],
)

history = model.fit(x_train, y_train, verbose = 1, epochs=40, batch_size = 32, validation_data=(x_valid, y_valid))

2022-11-13 06:18:01.076406: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2558720000 exceeds 10% of free system memory.
2022-11-13 06:18:04.271487: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 2558720000 exceeds 10% of free system memory.
2022-11-13 06:18:06.520581: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/40


2022-11-13 06:18:08.849157: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8005


313/313 [==============================] - ETA: 0s - loss: 0.4842 - precision: 0.5327 - recall: 0.4948

2022-11-13 06:18:50.951938: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 513280000 exceeds 10% of free system memory.
2022-11-13 06:18:51.237086: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 513280000 exceeds 10% of free system memory.


313/313 [==============================] - 47s 121ms/step - loss: 0.4842 - precision: 0.5327 - recall: 0.4948 - val_loss: 0.7566 - val_precision: 0.4144 - val_recall: 0.5915
Epoch 2/40
313/313 [==============================] - 36s 116ms/step - loss: 0.3598 - precision: 0.7453 - recall: 0.5170 - val_loss: 0.7531 - val_precision: 0.4255 - val_recall: 0.5896
Epoch 3/40
313/313 [==============================] - 36s 116ms/step - loss: 0.3178 - precision: 0.7949 - recall: 0.5508 - val_loss: 0.3428 - val_precision: 0.8089 - val_recall: 0.5547
Epoch 4/40
313/313 [==============================] - 36s 116ms/step - loss: 0.2881 - precision: 0.8238 - recall: 0.5957 - val_loss: 0.2971 - val_precision: 0.7900 - val_recall: 0.6152
Epoch 5/40
313/313 [==============================] - 36s 116ms/step - loss: 0.2595 - precision: 0.8394 - recall: 0.6425 - val_loss: 0.2507 - val_precision: 0.8613 - val_recall: 0.6499
Epoch 6/40
313/313 [==============================] - 36s 116ms/step - loss: 0.2355 - 

KeyboardInterrupt: 

In [19]:
model.save('model1_CNN.h5')

In [11]:
yhat_probs = model.predict(x_valid, verbose=1)

2022-11-13 06:40:04.839784: W tensorflow/core/framework/cpu_allocator_impl.cc:80] Allocation of 513280000 exceeds 10% of free system memory.


63/63 [==============================] - 2s 23ms/step


In [12]:
yhat1 = yhat_probs.round()

In [13]:
print(yhat1)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [14]:
print(y_valid)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [3]:
events_types = ['Alarm_bell_ringing', 'Blender','Cat','Dishes','Dog','Electric_shaver_toothbrush','Frying','Running_water','Speech','Vacuum_cleaner']

In [16]:
from sklearn.metrics import classification_report
report = classification_report(y_valid, yhat1, output_dict=True, target_names = events_types)
report_df = pd.DataFrame(report).transpose()

/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
report_df

precision    recall  f1-score  support
Alarm_bell_ringing           0.585062  0.479592  0.527103    294.0
Blender                      0.587571  0.454148  0.512315    229.0
Cat                          0.472656  0.557604  0.511628    217.0
Dishes                       0.681416  0.445946  0.539090    518.0
Dog                          0.481633  0.385621  0.428312    306.0
Electric_shaver_toothbrush   0.969512  0.732719  0.834646    217.0
Frying                       1.000000  0.723849  0.839806    239.0
Running_water                0.936416  0.642857  0.762353    252.0
Speech                       0.900800  0.973487  0.935734   1735.0
Vacuum_cleaner               0.957831  0.771845  0.854839    206.0
micro avg                    0.802573  0.725611  0.762154   4213.0
macro avg                    0.757290  0.616767  0.674583   4213.0
weighted avg                 0.796355  0.725611  0.751760   4213.0
samples avg                  0.796342  0.732461  0.738728   4213.0

In [18]:
report_df.to_csv("Model_1_val.csv")

In [4]:
model1 = tf.keras.models.load_model('../input/model-1-cnn/model1_CNN (1).h5')

2022-11-13 10:22:41.767473: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 10:22:41.883228: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 10:22:41.884034: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:937] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-11-13 10:22:41.885884: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compil

In [5]:
x_test = []
for m in range(2500):
    z = np.load("../input/test-set/test/X/melspec_" + str(m) + ".npy")
    z = np.reshape(z,(64,1000,1))
    x_test.append(z)
x_test = np.array(x_test)
x_test.shape

(2500, 64, 1000, 1)

In [6]:
model1.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 62, 998, 32)       320       
_________________________________________________________________
batch_normalization (BatchNo (None, 62, 998, 32)       128       
_________________________________________________________________
dropout (Dropout)            (None, 62, 998, 32)       0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 60, 996, 64)       18496     
_________________________________________________________________
batch_normalization_1 (Batch (None, 60, 996, 64)       256       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 30, 498, 64)       0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 30, 498, 64)       0

In [7]:
yhat_probs = model1.predict(x_test, verbose=1)
yhat1 = yhat_probs.round()
print(yhat1)
print(len(yhat1))

2022-11-13 10:23:08.945236: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
2022-11-13 10:23:09.982852: I tensorflow/stream_executor/cuda/cuda_dnn.cc:369] Loaded cuDNN version 8005


79/79 [==============================] - 9s 23ms/step
[[0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]]
2500


In [8]:
lst = []
c = 0
for m in yhat1:
    z = []
    if m[0] == 1:
        z.append(events_types[0])
    if m[1] == 1:
        z.append(events_types[1])
    if m[2] == 1:
        z.append(events_types[2])
    if m[3] == 1:
        z.append(events_types[3])
    if m[4] == 1:
        z.append(events_types[4])
    if m[5] == 1:
        z.append(events_types[5])
    if m[6] == 1:
        z.append(events_types[6])
    if m[7] == 1:
        z.append(events_types[7])
    if m[8] == 1:
        z.append(events_types[8])
    if m[9] == 1:
        z.append(events_types[9])
    lst.append(z)

In [9]:
lst

[['Dog', 'Speech'],
 ['Frying', 'Speech'],
 ['Electric_shaver_toothbrush', 'Speech'],
 ['Cat', 'Speech'],
 ['Alarm_bell_ringing', 'Speech'],
 ['Cat', 'Dog', 'Speech'],
 ['Alarm_bell_ringing', 'Speech'],
 ['Speech', 'Vacuum_cleaner'],
 ['Alarm_bell_ringing', 'Speech'],
 ['Speech'],
 ['Speech'],
 ['Speech'],
 ['Blender', 'Speech'],
 ['Speech'],
 ['Speech'],
 ['Speech'],
 ['Alarm_bell_ringing', 'Speech'],
 ['Cat', 'Speech'],
 ['Blender', 'Speech'],
 ['Speech', 'Vacuum_cleaner'],
 ['Frying', 'Speech'],
 ['Speech'],
 ['Cat', 'Speech'],
 ['Dog', 'Speech'],
 ['Speech'],
 ['Alarm_bell_ringing', 'Speech'],
 ['Dishes', 'Speech'],
 ['Dog', 'Speech'],
 ['Blender', 'Speech'],
 ['Cat', 'Speech'],
 ['Speech'],
 ['Running_water', 'Speech'],
 ['Dog', 'Speech'],
 ['Speech'],
 ['Dishes', 'Speech'],
 ['Running_water', 'Speech'],
 ['Speech'],
 ['Dishes', 'Frying', 'Speech'],
 ['Cat', 'Speech'],
 ['Speech'],
 ['Dog', 'Speech'],
 ['Speech'],
 ['Blender', 'Speech'],
 ['Dishes', 'Speech'],
 ['Dishes', 'Frying'

In [10]:
lst_names = []
for m in range(2500):
    lst_names.append("melspec_" + str(m) + ".npy")
lst_names

['melspec_0.npy',
 'melspec_1.npy',
 'melspec_2.npy',
 'melspec_3.npy',
 'melspec_4.npy',
 'melspec_5.npy',
 'melspec_6.npy',
 'melspec_7.npy',
 'melspec_8.npy',
 'melspec_9.npy',
 'melspec_10.npy',
 'melspec_11.npy',
 'melspec_12.npy',
 'melspec_13.npy',
 'melspec_14.npy',
 'melspec_15.npy',
 'melspec_16.npy',
 'melspec_17.npy',
 'melspec_18.npy',
 'melspec_19.npy',
 'melspec_20.npy',
 'melspec_21.npy',
 'melspec_22.npy',
 'melspec_23.npy',
 'melspec_24.npy',
 'melspec_25.npy',
 'melspec_26.npy',
 'melspec_27.npy',
 'melspec_28.npy',
 'melspec_29.npy',
 'melspec_30.npy',
 'melspec_31.npy',
 'melspec_32.npy',
 'melspec_33.npy',
 'melspec_34.npy',
 'melspec_35.npy',
 'melspec_36.npy',
 'melspec_37.npy',
 'melspec_38.npy',
 'melspec_39.npy',
 'melspec_40.npy',
 'melspec_41.npy',
 'melspec_42.npy',
 'melspec_43.npy',
 'melspec_44.npy',
 'melspec_45.npy',
 'melspec_46.npy',
 'melspec_47.npy',
 'melspec_48.npy',
 'melspec_49.npy',
 'melspec_50.npy',
 'melspec_51.npy',
 'melspec_52.npy',
 'm

In [11]:
import pandas as pd
df = pd.DataFrame(list(zip(lst_names, lst)),
               columns =['fileid', 'prediction'])
df

fileid                            prediction
0        melspec_0.npy                         [Dog, Speech]
1        melspec_1.npy                      [Frying, Speech]
2        melspec_2.npy  [Electric_shaver_toothbrush, Speech]
3        melspec_3.npy                         [Cat, Speech]
4        melspec_4.npy          [Alarm_bell_ringing, Speech]
...                ...                                   ...
2495  melspec_2495.npy                      [Dishes, Speech]
2496  melspec_2496.npy                         [Dog, Speech]
2497  melspec_2497.npy              [Dishes, Frying, Speech]
2498  melspec_2498.npy  [Electric_shaver_toothbrush, Speech]
2499  melspec_2499.npy              [Dishes, Frying, Speech]

[2500 rows x 2 columns]

In [12]:
df.to_csv("model_1_CNN_test_result.csv")